global:
  scrape_interval: 15s
scrape_configs:
  - job_name: collector
    static_configs:
      - targets: ["otel-collector:8889"]
  - job_name: runner
    static_configs:
      - targets: ["runner:4001"]
  - job_name: dashboard
    metrics_path: /metrics
    static_configs:
      - targets: ["dashboard:4000"]
