apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-redis-auth
  namespace: ai-arena
spec:
  secretTargetRef:
    - parameter: password
      name: arena-db-auth
      key: REDIS_PASSWORD
